# syntax=docker/dockerfile:1
FROM alpine
LABEL maintainer="Gzxhwq <gzxhwq@gmail.com>"
RUN set -ex \
    && apk add --no-cache --upgrade bash ca-certificates iptables nftables tzdata
COPY --from=gzxhwq/sing-box:client /usr/local/bin/sing-box /usr/local/bin/sing-box
COPY sb-redir /usr/local/bin/sb-redir
ENTRYPOINT ["/usr/local/bin/sb-redir"]
